name: build-windows-v2
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: simple_live_app
        shell: bash

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Flutter 3.22.x"
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.2'

      - name: "Enable Windows desktop"
        run: flutter config --enable-windows-desktop

      - name: "Clean lockfile"
        run: rm -f pubspec.lock

      # 尝试 1：覆盖 intl + 升级 media_kit_video（尽量保持较新依赖）
      - name: "Write overrides (try1: intl + media_kit_video)"
        run: |
          cat > pubspec_overrides.yaml <<'EOF'
          dependency_overrides:
            intl: 0.20.2
            media_kit_video: ^1.4.0
          EOF
          echo "=== pubspec_overrides.yaml (try1) ==="
          cat pubspec_overrides.yaml

      - name: "Pub get (try1)"
        id: pubget1
        run: flutter pub get
        continue-on-error: true

      # 如果 try1 失败，则回退：intl + 降级 screen_brightness 以兼容 media_kit_video 1.2.x
      - name: "Write overrides (fallback: intl + screen_brightness)"
        if: ${{ steps.pubget1.outcome == 'failure' }}
        run: |
          cat > pubspec_overrides.yaml <<'EOF'
          dependency_overrides:
            intl: 0.20.2
            screen_brightness: ^0.2.2+1
          EOF
          echo "=== pubspec_overrides.yaml (fallback) ==="
          cat pubspec_overrides.yaml

      - name: "Pub get (fallback)"
        if: ${{ steps.pubget1.outcome == 'failure' }}
        run: flutter pub get

      - name: "Show resolved versions"
        run: dart pub deps | grep -E "intl|media_kit_video|screen_brightness" || true

      - name: "Build Release"
        run: flutter build windows --release

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: simple_live_app-windows
          path: build/windows/x64/runner/Release/
