name: build-windows-v3
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: simple_live_app
        shell: bash

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Flutter 3.22.x"
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.2'

      - name: "Enable Windows desktop"
        run: flutter config --enable-windows-desktop

      - name: "Clean lockfile"
        run: rm -f pubspec.lock

      # 覆盖依赖：与 Flutter 3.22 匹配并让 media_kit_video 与 2.x 的 screen_brightness 共存
      - name: "Write pubspec_overrides.yaml (pin compat versions)"
        run: |
          cat > pubspec_overrides.yaml <<'EOF'
          dependency_overrides:
            intl: 0.20.2
            media_kit_video: ^1.3.0
            media_kit: ^1.2.0
            volume_controller: ^3.0.2
          EOF
          echo "=== pubspec_overrides.yaml ==="
          cat pubspec_overrides.yaml

      - name: "Pub get"
        run: flutter pub get

      # 屏蔽 Windows 侧的原生插件，避免 CMake/本地代码编译
      - name: "Patch generated Windows plugin files (drop problematic plugins)"
        run: |
          set -e
          GEN_DIR="windows/flutter"
          # 1) 从 CMake 列表移除
          sed -i '/media_kit_libs_windows_video/d' "${GEN_DIR}/generated_plugins.cmake" || true
          sed -i '/screen_brightness_windows/d'     "${GEN_DIR}/generated_plugins.cmake" || true
          # 2) 从 C++ registrant 中移除 include/注册
          REG_CC="${GEN_DIR}/generated_plugin_registrant.cc"
          if [ -f "${REG_CC}" ]; then
            sed -i '/media_kit_libs_windows_video/d' "${REG_CC}" || true
            sed -i '/screen_brightness_windows/d'     "${REG_CC}" || true
          fi

      - name: "Show resolved key deps"
        run: dart pub deps | grep -E "intl|media_kit|media_kit_video|screen_brightness|volume_controller" || true

      - name: "Build Release"
        run: flutter build windows --release

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: simple_live_app-windows
          path: build/windows/x64/runner/Release/
